server: 
  port: 2222
  tomcat:
    uri-encoding: UTF-8
  servlet.session:
    timeout: 800000000

tomcat:
  ajp:
    protocol: AJP/1.3
    port: 8029

spring:
  application:
    name: eBay Japan Morpheme analyzer
  profiles:
    active: local

---    
########################################################################
# 로컬                                                                                                                                                     #
########################################################################

spring:
  profiles: local
  mvc.static-path-pattern: /static/**
  server:
    port: 8050
---
spring:
    profiles: dev
server:
    port: 8081
---
spring:
    profiles: real
server:
    port: 2222
  
logging:
  config: classpath:logback-spring.xml
  level:
    com.eBayJP.kuromoji: debug
    org.springframework: info
    
           

spring.main.allow-bean-definition-overriding: true