
########################################################################
# 로컬                                                                                                                                                     #
########################################################################

spring:
  profiles: local
  mvc.static-path-pattern: /static/**


  
logging:
  config: classpath:logback-spring.xml
  level:
    com.eBayJP.kuromoji: debug
    org.springframework: info
#    DB 있을 경우 나중에 설정    
           

spring.main.allow-bean-definition-overriding: true